[package]
name = "youtube-channel-id-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.38"
reqwest = { version = "0.12.15", features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0"
url = "2.3"

